# Generated by Django 3.2.18 on 2023-04-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messa',
            new_name='Message',
        ),
    ]
