# Generated by Django 3.2.18 on 2023-04-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointing_poker', '0002_auto_20230403_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='users',
            field=models.ManyToManyField(to='pointing_poker.User'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointing_poker.gamesession')),
            ],
        ),
    ]
