# Generated by Django 3.2.18 on 2023-04-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointing_poker', '0004_participant_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pointing_poker.user'),
            preserve_default=False,
        ),
    ]
