# Generated by Django 3.2.18 on 2023-04-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing_poker', '0005_auto_20230403_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(default='defaul_name', max_length=255),
        ),
    ]
