# Generated by Django 3.2.18 on 2023-04-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointing_poker', '0006_participant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
