# Generated by Django 3.2.18 on 2023-04-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing_poker', '0007_remove_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
