# Generated by Django 3.2.18 on 2023-05-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_ticket', '0002_ticket_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
