# Generated by Django 3.2.18 on 2023-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_ticket', '0003_alter_ticket_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
