# Generated by Django 3.2.18 on 2023-05-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_ticket', '0004_ticket_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='last_modified',
        ),
    ]
