# Generated by Django 3.2.18 on 2023-03-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(default='Python', max_length=50),
        ),
    ]
