# Generated by Django 3.2.22 on 2023-12-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_snippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='chat_gpt_explanation',
            field=models.TextField(blank=True),
        ),
    ]
